---
name: Release
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0
      - name: Detect version change
        id: version-check
        run: |
          VERSION="$(sed -n 's/^VERSION=\([0-9\.]\+\)$/\1/p' VERSION)"
          if git rev-parse "v${VERSION}" > /dev/null 2>&1 ; then
              NEW_VERSION=false
          else
              NEW_VERSION=true
          fi
          {
              echo "VERSION=${VERSION}"
              echo "NEW_VERSION=${NEW_VERSION}"
          } >> "$GITHUB_OUTPUT"
      - name: Create GitHub release
        if: steps.version-check.outputs.NEW_VERSION == 'true'
        run: gh release create "$TAG" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: v${{ steps.version-check.outputs.VERSION }}
